#!/bin/bash
set -ex
export PERL5LIB=$PWD/vendor/lib/perl5:$PERL5LIB
export PERL_CARMEL_REPO=$PWD/.cache/carmel

./vendor/cpanm -nq -L ./vendor Carmel
./vendor/bin/carmel version

time (./vendor/bin/carmel install && ./vendor/bin/carmel rollout)


