#!/bin/bash
export PERL5LIB=$PWD/vendor/lib/perl5:$PERL5LIB

./vendor/cpanm -nq -L ./vendor Carton
./vendor/bin/carton version

time PERL_CARTON_MIRROR=file://$PWD/vendor/cache ./vendor/bin/carton install
